### ISSUE TITLE
Error: ModuleNotFoundError: No module named 'kinpy.urdf_parser_py' when importing kinpy

### ISSUE THREAD

**Issue by JeremySMorgan** [neka-nat/kinpy#4]
I've just installed kinpy with `python setup.py build` and `python setup.py install`. I can't use the package though, i'm getting the following error:

'''
>>> import kinpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kinpy/__init__.py", line 1, in <module>
    from .urdf import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/kinpy/urdf.py", line 1, in <module>
    from .urdf_parser_py.urdf import URDF, Mesh, Cylinder, Box, Sphere
ModuleNotFoundError: No module named 'kinpy.urdf_parser_py'
'''

How can this problem be fixed?

Thanks

**Comment by neka-nat** [comment]
Thanks!
I fixed it so you can try it out.
```
pip install -U kinpy
```

**Comment by JeremySMorgan** [comment]
Its working now! Thanks for the quick fix
